export default {
  Distance: [
    { label: "CentiMeter", value: "centimeter" },
    { label: "Feet", value: "feet" },
    { label: "Inch", value: "inch" },
    { label: "kiloMeter", value: "kilometer" },
    { label: "Meter", value: "meter" },
    { label: "Mile", value: "mile" },
    { label: "MilliMeter", value: "millimeter" },
    { label: "Yard", value: "yard" },
  ],
  Temperature: [
    { label: "Celsius", value: "celsius" },
    { label: "Kelvin", value: "kelvin" },
    { label: "Fahrenheit", value: "fahrenheit" },
  ],
  Currency: [
    { label: "UNITED ARAB EMIRATES (AED)", value: "AED" },
    { label: "AUSTRALIA (AUD)", value: "AUD" },
    { label: "EUROPEAN UNION (EUR)", value: "EUR" },
    {
      label: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (GBP)",
      value: "GBP",
    },
    { label: "INDIA (INR)", value: "INR" },
    { label: "JAPAN (JPY)", value: "JPY" },
    { label: "KUWAIT (KWD)", value: "KWD" },
    { label: "MEXICO (MXN)", value: "MXN" },
    { label: "MALAYSIA (MYR)", value: "MYR" },
    { label: "SINGAPORE (SGD)", value: "SGD" },
    { label: "UNITED STATES OF AMERICA (USD)", value: "USD" },
  ],
  Time: [
    { label: "Seconds (s)", value: "seconds" },
    { label: "Minute (min)", value: "minute" },
    { label: "Hour (h)", value: "hour" },
    { label: "Day (d)", value: "day" },
    { label: "Week ", value: "week" },
    { label: "Month ", value: "month" },
    { label: "Year ", value: "year" },
  ],
  Number: [
    { label: "Binary", value: "binary", base: 2 },
    { label: "Quinary", value: "quinary", base: 5 },
    { label: "Octal", value: "octal", base: 8 },
    { label: "Decimal", value: "decimal", base: 10 },
    { label: "Hexadecimal", value: "hexadecimal", base: 16 },
  ],
};
